### ISSUE TITLE
Suggestion: Pass dropt_option to handlers

### ISSUE THREAD

**Issue by ajayre** [jamesderlin/dropt#1]
Not an issue but a suggestion. If you allow passing of dropt_option with the current option to the handlers then it becomes possible to write a single generic handler.  E.g.:

... my_generic_handler(..., dropt_option *option, ...) {
  switch(option->short_name) {
    case 'x':
      ...
      break;
  }
  ..
}

Why do this? I am writing an application that executes commands. The commands are specified on the command line in the order of execution, and there may be multiple of the same command. E.g.:

MyApp --reset --read --reset --write --settime=3 --write --settime=4 --write

By using a generic handler I can call it for multiple command line options and build a linked list of commands to execute, and I only have to write the handler code once. Note - inside my generic handler I make a call to the built-in handlers, e.g. option->handler();

Thanks.

**Comment by jamesderlin** [comment]
Hi! (Sorry that I didn't respond earlier; somehow I wasn't notified that this issue was filed.)

Yes, passing along the dropt_option to handlers seems like it could be useful, so that sounds like a reasonable request.  I think the only real obstacle is a concern about breaking API compatibility, but that might be worth it.  I will definitely consider your suggestion.

Thanks!

**Comment by kravemir** [comment]
> Hi! (Sorry that I didn't respond earlier; somehow I wasn't notified that this issue was filed.)

@jamesderlin you should add yourself to the project watchers to receive notifications. It's good to be watcher of your own project.
