### ISSUE TITLE
option for required argument?

### ISSUE THREAD

**Issue by esromneb** [jamesderlin/dropt#5]
I am looking for a way to make an argument required.  I see the `dropt_attr_optional_val` but can you add a required version?

**Comment by jamesderlin** [comment]
If an option is configured to take an argument, the argument is required by default (unless `dropt_attr_optional_val` is specified).

Do you have a specific example where that doesn't behave the way that you want?

**Comment by jamesderlin** [comment]
Also, to be clear: are you asking to make an *option*'s argument required (e.g. `--option=REQUIRED_ARGUMENT`), or are you asking to make an option itself required (e.g. `--some_required_option`)?

**Comment by esromneb** [comment]
I'm asking for `--some_required_option`.  I hope that makes it clear, if not I can give an example.

In my case I want this for an int, so it would be `--some_required_option=4` or `--some_required_option=10` or whatever the user passes

**Comment by jamesderlin** [comment]
Currently you'd need to make `--some_required_option` write to some variable and later verify that it was modified:

```c
int required_value = INT_MAX; // Or some other suitable sentinel value.
dropt_option options[] =
{
    ...
    { '\0', "some_required_option", "description", "ARG", dropt_handle_int, &required_value },
    { 0 }
};
...
char** rest = dropt_parse(droptContext, -1, &argv[1]);
...
if (required_value == INT_MAX)
{
    // Print an error and abort.
}
```

If there is no suitable sentinel value, you could handle it as a string and parse it later:

```c
char* required_value_str = NULL;
dropt_option options[] =
{
    ...
    { '\0', "some_required_option", "description", "ARG", dropt_handle_int, &required_value_str },
    { 0 }
};
...
char** rest = dropt_parse(droptContext, -1, &argv[1]);
...
if (required_value_str == NULL)
{
    // Print an error and abort.
}
int required_value;
dropt_error error = dropt_handle_int(droptContext, NULL, required_value_str, &required_value);
if (error != dropt_error_none)
{
    // Print an error and abort.
}
```

**Comment by jamesderlin** [comment]
I'll spend some time thinking if there's a good way to allow dropt to support required options directly, but I suspect that it will be unlikely.

**Comment by esromneb** [comment]
Ok thanks! These examples are helpful!

**Comment by jamesderlin** [comment]
I'm sorry, but after some deliberation, I've decided not to implement this.

In general, required options aren't an isolated feature and have implications on how things like `--help` and `--version` are handled (where even "required" options shouldn't actually be required in some cases). [This problem arose](https://github.com/dart-lang/core/issues/67) when required options were recently bolted onto the commonly-used argument parser for the Dart ecosystem. dropt *maybe* would start off in a slightly better position since it likely could leverage `dropt_attr_halt` to identify such cases, but it's still extra complexity that I'd prefer to avoid. (dropt really is *deliberately rudimentary*.)

I think ultimately it'd be better to document this scenario with examples, perhaps in an FAQ.
